### ISSUE TITLE
Fix two minor bugs in `db:import_all_seeds` rake task.

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#719]
Ran into a couple of errors attempting to run `rake db:import_all_seeds` into the demo env.

1. Ran into a `ContactMethod` with a `nil` `field`. I see this both in demo and local, so i suspect something in our seeding is creating that row:
```
NoMethodError: undefined method `downcase' for nil:NilClass
/app/db/seeds/dev_seeds.rb:35:in `block in <main>'
```

2. Trying to create `User` records with a too-short password:
```
ActiveRecord::RecordInvalid: Validation failed: Password is too short (minimum is 8 characters)
...
/app/db/seeds/dev_seeds.rb:171:in `block in <main>'
```

**Comment by kinduff** [comment]
@exbinary Happy to take this one!

**Comment by exbinary** [comment]
That would be great, thank you @kinduff ⚡️!!
